/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static project.Principal.total;



/**
 *
 * @author Void
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    static String tot;
    static int total;
    boolean imageChooser = false;
    String path;
    
    public AdminPanel() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        atualizar1Btn = new javax.swing.JButton();
        controleEstoqueBtn = new javax.swing.JButton();
        faturamentoBtn = new javax.swing.JButton();
        cardAdminParentLayout = new javax.swing.JPanel();
        controlaEstoquePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        controlaEstoqueTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        modeloAddCampo = new javax.swing.JTextField();
        categoria2ComboBox = new javax.swing.JComboBox<>();
        atualizaEstoqueBtn = new javax.swing.JButton();
        removerEstoqueBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        modeloDelCampo = new javax.swing.JTextField();
        categoria3ComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        atualizaQtdeCampo = new javax.swing.JTextField();
        faturamentoPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        faturamentoTable = new javax.swing.JTable();
        apagarFaturamentoBtn = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        trimestralLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        consultaDataBtn = new javax.swing.JButton();
        dataInicialCampo = new javax.swing.JTextField();
        dataFinalCampo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        atualizarPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        marcaCampo = new javax.swing.JTextField();
        modeloCampo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        qtdeCampo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        localImagemCampo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        categoriaComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoCampo = new javax.swing.JTextArea();
        imagemSelecionadaCampo = new javax.swing.JLabel();
        imagemSelecionadaBtn = new javax.swing.JButton();
        precoCampo = new javax.swing.JTextField();
        atualizar2Btn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        precoAquisicaoCampo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        notaProcelCampo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(1199, 699));
        jPanel3.setPreferredSize(new java.awt.Dimension(1199, 699));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(25, 25, 112));
        jPanel2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 72));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Espaço do Administrador");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Admin_48px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(678, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 60));

        jPanel4.setBackground(new java.awt.Color(64, 224, 208));

        atualizar1Btn.setBackground(new java.awt.Color(64, 224, 208));
        atualizar1Btn.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        atualizar1Btn.setForeground(new java.awt.Color(255, 255, 255));
        atualizar1Btn.setText("Novo produto");
        atualizar1Btn.setToolTipText("Entre com um novo produto.");
        atualizar1Btn.setBorder(null);
        atualizar1Btn.setBorderPainted(false);
        atualizar1Btn.setContentAreaFilled(false);
        atualizar1Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        atualizar1Btn.setOpaque(true);
        atualizar1Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizar1BtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atualizar1BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atualizar1BtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                atualizar1BtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                atualizar1BtnMouseReleased(evt);
            }
        });
        atualizar1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizar1BtnActionPerformed(evt);
            }
        });

        controleEstoqueBtn.setBackground(new java.awt.Color(64, 224, 208));
        controleEstoqueBtn.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        controleEstoqueBtn.setForeground(new java.awt.Color(255, 255, 255));
        controleEstoqueBtn.setText("Controlar estoque");
        controleEstoqueBtn.setToolTipText("Situação do estoque");
        controleEstoqueBtn.setBorder(null);
        controleEstoqueBtn.setBorderPainted(false);
        controleEstoqueBtn.setContentAreaFilled(false);
        controleEstoqueBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        controleEstoqueBtn.setOpaque(true);
        controleEstoqueBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                controleEstoqueBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                controleEstoqueBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                controleEstoqueBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                controleEstoqueBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                controleEstoqueBtnMouseReleased(evt);
            }
        });
        controleEstoqueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controleEstoqueBtnActionPerformed(evt);
            }
        });

        faturamentoBtn.setBackground(new java.awt.Color(64, 224, 208));
        faturamentoBtn.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        faturamentoBtn.setForeground(new java.awt.Color(255, 255, 255));
        faturamentoBtn.setText("Faturamento");
        faturamentoBtn.setToolTipText("Faturamento total");
        faturamentoBtn.setBorder(null);
        faturamentoBtn.setBorderPainted(false);
        faturamentoBtn.setContentAreaFilled(false);
        faturamentoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        faturamentoBtn.setOpaque(true);
        faturamentoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                faturamentoBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                faturamentoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                faturamentoBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                faturamentoBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                faturamentoBtnMouseReleased(evt);
            }
        });
        faturamentoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faturamentoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(atualizar1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(controleEstoqueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(faturamentoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(720, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(controleEstoqueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizar1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faturamentoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 1210, 50));

        cardAdminParentLayout.setBackground(new java.awt.Color(255, 255, 255));
        cardAdminParentLayout.setLayout(new java.awt.CardLayout());

        controlaEstoquePanel.setBackground(new java.awt.Color(255, 255, 255));

        controlaEstoqueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Estoque", "Categoria"
            }
        ));
        controlaEstoqueTable.setEnabled(false);
        controlaEstoqueTable.setRowHeight(20);
        jScrollPane3.setViewportView(controlaEstoqueTable);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(25, 25, 112));
        jLabel10.setText("Modelo :");
        jLabel10.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(25, 25, 112));
        jLabel11.setText("Adiciona ao estoque");

        modeloAddCampo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        modeloAddCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloAddCampoActionPerformed(evt);
            }
        });

        categoria2ComboBox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        categoria2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Iluminação", "Hidráulica", "Eletro" }));

        atualizaEstoqueBtn.setBackground(new java.awt.Color(25, 25, 112));
        atualizaEstoqueBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        atualizaEstoqueBtn.setForeground(new java.awt.Color(255, 255, 255));
        atualizaEstoqueBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Up_24px.png"))); // NOI18N
        atualizaEstoqueBtn.setText("Atualizar estoque");
        atualizaEstoqueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaEstoqueBtnActionPerformed(evt);
            }
        });

        removerEstoqueBtn.setBackground(new java.awt.Color(255, 0, 0));
        removerEstoqueBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        removerEstoqueBtn.setForeground(new java.awt.Color(255, 255, 255));
        removerEstoqueBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Delete_24px.png"))); // NOI18N
        removerEstoqueBtn.setText("Remover produto");
        removerEstoqueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerEstoqueBtnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Remover do estoque");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("Modelo :");

        modeloDelCampo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        modeloDelCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloDelCampoActionPerformed(evt);
            }
        });

        categoria3ComboBox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        categoria3ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Iluminação", "Hidráulica", "Eletro" }));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(25, 25, 112));
        jLabel14.setText("Quantidade :");

        atualizaQtdeCampo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        atualizaQtdeCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaQtdeCampoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlaEstoquePanelLayout = new javax.swing.GroupLayout(controlaEstoquePanel);
        controlaEstoquePanel.setLayout(controlaEstoquePanelLayout);
        controlaEstoquePanelLayout.setHorizontalGroup(
            controlaEstoquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(controlaEstoquePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlaEstoquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(controlaEstoquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlaEstoquePanelLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modeloDelCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(categoria3ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(removerEstoqueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(controlaEstoquePanelLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modeloAddCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(categoria2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atualizaQtdeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(atualizaEstoqueBtn)
                .addGap(61, 61, 61))
        );
        controlaEstoquePanelLayout.setVerticalGroup(
            controlaEstoquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlaEstoquePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(controlaEstoquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlaEstoquePanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(controlaEstoquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modeloAddCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlaEstoquePanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(controlaEstoquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoria2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atualizaQtdeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atualizaEstoqueBtn))))
                .addGap(27, 27, 27)
                .addGroup(controlaEstoquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlaEstoquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modeloDelCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlaEstoquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(categoria3ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(removerEstoqueBtn)))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        cardAdminParentLayout.add(controlaEstoquePanel, "card4");

        faturamentoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial", "Nome", "Fatura Total", "Data"
            }
        ));
        jScrollPane2.setViewportView(faturamentoTable);

        apagarFaturamentoBtn.setBackground(new java.awt.Color(255, 0, 0));
        apagarFaturamentoBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        apagarFaturamentoBtn.setForeground(new java.awt.Color(255, 255, 255));
        apagarFaturamentoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Delete_24px.png"))); // NOI18N
        apagarFaturamentoBtn.setText("Apagar faturamento");
        apagarFaturamentoBtn.setToolTipText("");
        apagarFaturamentoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarFaturamentoBtnActionPerformed(evt);
            }
        });

        totalLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel17.setText("Faturamento total :");

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel19.setText("Lucro líquido :");

        consultaDataBtn.setBackground(new java.awt.Color(0, 0, 255));
        consultaDataBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        consultaDataBtn.setForeground(new java.awt.Color(255, 255, 255));
        consultaDataBtn.setText("Consultar por data");
        consultaDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaDataBtnActionPerformed(evt);
            }
        });

        dataInicialCampo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        dataFinalCampo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel18.setText("Data inicial :");

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel20.setText("Data final :");
        jLabel20.setToolTipText("");

        javax.swing.GroupLayout faturamentoPanelLayout = new javax.swing.GroupLayout(faturamentoPanel);
        faturamentoPanel.setLayout(faturamentoPanelLayout);
        faturamentoPanelLayout.setHorizontalGroup(
            faturamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
            .addGroup(faturamentoPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(apagarFaturamentoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(consultaDataBtn)
                .addGap(18, 18, 18)
                .addGroup(faturamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(faturamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dataFinalCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(dataInicialCampo))
                .addGap(27, 27, 27)
                .addGroup(faturamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(faturamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(trimestralLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        faturamentoPanelLayout.setVerticalGroup(
            faturamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faturamentoPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(faturamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(faturamentoPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(faturamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(faturamentoPanelLayout.createSequentialGroup()
                                .addGroup(faturamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(faturamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dataInicialCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(faturamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(trimestralLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(faturamentoPanelLayout.createSequentialGroup()
                                        .addGroup(faturamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(dataFinalCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 8, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, faturamentoPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20)))
                        .addGap(19, 19, 19))
                    .addGroup(faturamentoPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(faturamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(consultaDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apagarFaturamentoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        cardAdminParentLayout.add(faturamentoPanel, "card2");

        atualizarPanel.setBackground(new java.awt.Color(255, 255, 255));
        atualizarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 25, 112));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Informações do Produto");
        atualizarPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, 1200, -1));

        jSeparator1.setBackground(new java.awt.Color(25, 25, 112));
        jSeparator1.setForeground(new java.awt.Color(25, 25, 112));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSeparator1.setOpaque(true);
        jSeparator1.setPreferredSize(new java.awt.Dimension(0, 1));
        atualizarPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 51, 200, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 25, 112));
        jLabel4.setText("Marca :");
        atualizarPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 104, 50));

        marcaCampo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        marcaCampo.setForeground(new java.awt.Color(25, 25, 112));
        marcaCampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 77, 64)));
        marcaCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaCampoActionPerformed(evt);
            }
        });
        atualizarPanel.add(marcaCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 79, 362, 30));

        modeloCampo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        modeloCampo.setForeground(new java.awt.Color(25, 25, 112));
        modeloCampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 77, 64)));
        modeloCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloCampoActionPerformed(evt);
            }
        });
        atualizarPanel.add(modeloCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 119, 362, 30));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(25, 25, 112));
        jLabel5.setText("Modelo :");
        jLabel5.setToolTipText("");
        atualizarPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 104, 50));

        qtdeCampo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        qtdeCampo.setForeground(new java.awt.Color(25, 25, 112));
        qtdeCampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 77, 64)));
        qtdeCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdeCampoActionPerformed(evt);
            }
        });
        atualizarPanel.add(qtdeCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 199, 110, 30));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 25, 112));
        jLabel6.setText("Categoria :");
        jLabel6.setToolTipText("");
        atualizarPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 104, -1));

        localImagemCampo.setEditable(false);
        localImagemCampo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        localImagemCampo.setForeground(new java.awt.Color(25, 25, 112));
        localImagemCampo.setText("Escolha a imagem :");
        localImagemCampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 77, 64)));
        localImagemCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localImagemCampoActionPerformed(evt);
            }
        });
        atualizarPanel.add(localImagemCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 210, 30));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(25, 25, 112));
        jLabel7.setText("Preço de Venda :");
        jLabel7.setToolTipText("");
        atualizarPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 104, 50));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(25, 25, 112));
        jLabel8.setText("Quantidade :");
        atualizarPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 104, 50));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(25, 25, 112));
        jLabel9.setText("Descrição do produto :");
        jLabel9.setToolTipText("");
        atualizarPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 170, -1));

        categoriaComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        categoriaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Iluminação", "Hidráulica", "Eletro" }));
        atualizarPanel.add(categoriaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));

        descricaoCampo.setColumns(20);
        descricaoCampo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        descricaoCampo.setLineWrap(true);
        descricaoCampo.setRows(5);
        descricaoCampo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 77, 64), 1, true));
        jScrollPane1.setViewportView(descricaoCampo);

        atualizarPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 401, 370, 170));

        imagemSelecionadaCampo.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        imagemSelecionadaCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagemSelecionadaCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Add_Image_100px.png"))); // NOI18N
        imagemSelecionadaCampo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 77, 64), 1, true));
        imagemSelecionadaCampo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        atualizarPanel.add(imagemSelecionadaCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, 230, 210));

        imagemSelecionadaBtn.setBackground(new java.awt.Color(25, 25, 112));
        imagemSelecionadaBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        imagemSelecionadaBtn.setForeground(new java.awt.Color(255, 255, 255));
        imagemSelecionadaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Add_Camera_20px.png"))); // NOI18N
        imagemSelecionadaBtn.setBorder(null);
        imagemSelecionadaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imagemSelecionadaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagemSelecionadaBtnActionPerformed(evt);
            }
        });
        atualizarPanel.add(imagemSelecionadaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 340, 50, 30));

        precoCampo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        precoCampo.setForeground(new java.awt.Color(25, 25, 112));
        precoCampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 77, 64)));
        precoCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoCampoActionPerformed(evt);
            }
        });
        atualizarPanel.add(precoCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 159, 180, 30));

        atualizar2Btn.setBackground(new java.awt.Color(25, 25, 112));
        atualizar2Btn.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        atualizar2Btn.setForeground(new java.awt.Color(255, 255, 255));
        atualizar2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Add_Database_24px.png"))); // NOI18N
        atualizar2Btn.setText("Atualizar");
        atualizar2Btn.setBorder(null);
        atualizar2Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        atualizar2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizar2BtnActionPerformed(evt);
            }
        });
        atualizarPanel.add(atualizar2Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 460, 130, 50));

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(25, 25, 112));
        jLabel15.setText("Preço de Aquisição :");
        atualizarPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, 50));

        precoAquisicaoCampo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        precoAquisicaoCampo.setForeground(new java.awt.Color(25, 25, 112));
        precoAquisicaoCampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 77, 64)));
        precoAquisicaoCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoAquisicaoCampoActionPerformed(evt);
            }
        });
        atualizarPanel.add(precoAquisicaoCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 220, 30));

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(25, 25, 112));
        jLabel16.setText("Nota Procel :");
        atualizarPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));
        atualizarPanel.add(notaProcelCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 220, 30));

        cardAdminParentLayout.add(atualizarPanel, "card3");

        jPanel3.add(cardAdminParentLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1200, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void faturamentoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faturamentoBtnActionPerformed
        // TODO add your handling code here:
            cardAdminParentLayout.removeAll();
            cardAdminParentLayout.add(faturamentoPanel);
            cardAdminParentLayout.repaint();
            cardAdminParentLayout.revalidate();
            
            
            DefaultTableModel model =  (DefaultTableModel) faturamentoTable.getModel();
            model.setRowCount(0);
         
            Object[] data = new Object[4];
            ArrayList<Fatura> list = new ArrayList<>();
            list = FaturamentoDAO.fatura();
        
        for(int i=0; i<list.size(); i++){
            data[0] = i+1;
            data[1] = list.get(i).getUsuarioNome();
            data[2] = list.get(i).getValor();
            data[3] = list.get(i).getData();
            
            model.addRow(data);
            faturamentoTable.setRowHeight(20);
            
            int Soma = Integer.parseInt(faturamentoTable.getValueAt(i, 2)+"");
            total = total + Soma;
        }
        
        totalLabel.setText(String.valueOf(total));
    }//GEN-LAST:event_faturamentoBtnActionPerformed

    private void faturamentoBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faturamentoBtnMouseReleased
        // TODO add your handling code here:
        faturamentoBtn.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_faturamentoBtnMouseReleased

    private void faturamentoBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faturamentoBtnMousePressed
        // TODO add your handling code here:
        faturamentoBtn.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_faturamentoBtnMousePressed

    private void faturamentoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faturamentoBtnMouseExited
        // TODO add your handling code here:
        faturamentoBtn.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_faturamentoBtnMouseExited

    private void faturamentoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faturamentoBtnMouseEntered
        // TODO add your handling code here:
        faturamentoBtn.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_faturamentoBtnMouseEntered

    private void faturamentoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faturamentoBtnMouseClicked

    }//GEN-LAST:event_faturamentoBtnMouseClicked

    private void controleEstoqueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controleEstoqueBtnActionPerformed
            cardAdminParentLayout.removeAll();
            cardAdminParentLayout.add(controlaEstoquePanel);
            cardAdminParentLayout.repaint();
            cardAdminParentLayout.revalidate();
            
            DefaultTableModel model =  (DefaultTableModel) controlaEstoqueTable.getModel();
            model.setRowCount(0);
         
            ArrayList<ProductList> list = IluminacaoDAO.confereEstoque();
        
            Object data[] = new Object[4];
        
        for(int i=0; i<list.size(); i++){
            data[0] = list.get(i).getMarca();
            data[1] = list.get(i).getModelo();
            data[2] = list.get(i).getQuantidade();
            data[3] = "Iluminação";
            
            model.addRow(data);
        }
        
        list.clear();
        
        list = HidraulicaDAO.confereEstoque();
        
        for(int i=0; i<list.size(); i++){
            data[0] = list.get(i).getMarca();
            data[1] = list.get(i).getModelo();
            data[2] = list.get(i).getQuantidade();
            data[3] = "Hidráulica";
            
            model.addRow(data);
        }
        
        list.clear();
        
        list = EletroDAO.confereEstoque();
        
        for(int i=0; i<list.size(); i++){
            data[0] = list.get(i).getMarca();
            data[1] = list.get(i).getModelo();
            data[2] = list.get(i).getQuantidade();
            data[3] = "Eletro";
            
            model.addRow(data);
        }
            
            
    }//GEN-LAST:event_controleEstoqueBtnActionPerformed

    private void controleEstoqueBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controleEstoqueBtnMouseReleased
        // TODO add your handling code here:
        controleEstoqueBtn.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_controleEstoqueBtnMouseReleased

    private void controleEstoqueBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controleEstoqueBtnMousePressed
        // TODO add your handling code here:
        controleEstoqueBtn.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_controleEstoqueBtnMousePressed

    private void controleEstoqueBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controleEstoqueBtnMouseExited
        // TODO add your handling code here:
        controleEstoqueBtn.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_controleEstoqueBtnMouseExited

    private void controleEstoqueBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controleEstoqueBtnMouseEntered
        // TODO add your handling code here:
        controleEstoqueBtn.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_controleEstoqueBtnMouseEntered

    private void controleEstoqueBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controleEstoqueBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_controleEstoqueBtnMouseClicked

    private void atualizar1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizar1BtnActionPerformed
            cardAdminParentLayout.removeAll();
            cardAdminParentLayout.add(atualizarPanel);
            cardAdminParentLayout.repaint();
            cardAdminParentLayout.revalidate();
    }//GEN-LAST:event_atualizar1BtnActionPerformed

    private void atualizar1BtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizar1BtnMouseReleased
        // TODO add your handling code here:
        atualizar1Btn.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_atualizar1BtnMouseReleased

    private void atualizar1BtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizar1BtnMousePressed
        // TODO add your handling code here:
        atualizar1Btn.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_atualizar1BtnMousePressed

    private void atualizar1BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizar1BtnMouseExited
        // TODO add your handling code here:
        atualizar1Btn.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_atualizar1BtnMouseExited

    private void atualizar1BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizar1BtnMouseEntered
        // TODO add your handling code here:;
        atualizar1Btn.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_atualizar1BtnMouseEntered

    private void atualizar1BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizar1BtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizar1BtnMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void marcaCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaCampoActionPerformed

    private void modeloCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloCampoActionPerformed

    private void qtdeCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdeCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtdeCampoActionPerformed

    private void localImagemCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localImagemCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localImagemCampoActionPerformed

    private void imagemSelecionadaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagemSelecionadaBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        File selectedImage = fc.getSelectedFile();
        path = selectedImage.getName();
        
        try {
            Image img = ImageIO.read(selectedImage);
            localImagemCampo.setText(path);
            imagemSelecionadaCampo.setIcon(new ImageIcon(img.getScaledInstance(imagemSelecionadaCampo.getWidth(),
                    imagemSelecionadaCampo.getHeight(), Image.SCALE_SMOOTH)));
        } catch (IOException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_imagemSelecionadaBtnActionPerformed

    private void precoCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoCampoActionPerformed

    private void atualizar2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizar2BtnActionPerformed
        // TODO add your handling code here:
        try{
            if(categoriaComboBox.getSelectedItem().equals("Hidráulica")){
            if(!path.equals(""))
                HidraulicaDAO.lancarHidraulica(marcaCampo.getText(), modeloCampo.getText(), Integer.parseInt(precoCampo.getText()), 
                        Integer.parseInt(qtdeCampo.getText()), descricaoCampo.getText(), path, Integer.parseInt(precoAquisicaoCampo.getText()),
                        notaProcelCampo.getText());
        }
        
        else if(categoriaComboBox.getSelectedItem().equals("Iluminação")){
            if(!path.equals(""))
                IluminacaoDAO.lancarIluminacao(marcaCampo.getText(), modeloCampo.getText(), Integer.parseInt(precoCampo.getText()), 
                        Integer.parseInt(qtdeCampo.getText()), descricaoCampo.getText(), path, Integer.parseInt(precoAquisicaoCampo.getText()),
                        notaProcelCampo.getText());
        }
        else if(categoriaComboBox.getSelectedItem().equals("Eletro")){
            if(!path.equals(""))
                EletroDAO.lancarEletro(marcaCampo.getText(), modeloCampo.getText(), Integer.parseInt(precoCampo.getText()), 
                        Integer.parseInt(qtdeCampo.getText()), descricaoCampo.getText(), path, Integer.parseInt(precoAquisicaoCampo.getText()),
                        notaProcelCampo.getText());
        }
        
        marcaCampo.setText("");
        modeloCampo.setText("");
        qtdeCampo.setText("");
        precoCampo.setText("");
        descricaoCampo.setText("");
        localImagemCampo.setText("");
        precoAquisicaoCampo.setText("");
        notaProcelCampo.setText("");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            marcaCampo.setText("");
            modeloCampo.setText("");
            qtdeCampo.setText("");
            precoCampo.setText("");
            descricaoCampo.setText("");
            localImagemCampo.setText("");
            precoAquisicaoCampo.setText("");
            notaProcelCampo.setText("");
        }


    }//GEN-LAST:event_atualizar2BtnActionPerformed

    private void modeloAddCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloAddCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloAddCampoActionPerformed

    private void modeloDelCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloDelCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloDelCampoActionPerformed

    private void atualizaEstoqueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaEstoqueBtnActionPerformed
        // TODO add your handling code here:
       try{
            String model = modeloAddCampo.getText();
            int qty = Integer.parseInt(atualizaQtdeCampo.getText());

            if(categoria2ComboBox.getSelectedItem().equals("Iluminacao")){
                IluminacaoDAO.flag = true;
                IluminacaoDAO.atualizarIluminacao(model, qty);
            }

            else if(categoria2ComboBox.getSelectedItem().equals("Hidraulica")){
                HidraulicaDAO.flag = true;
                HidraulicaDAO.atualizarHidraulica(model, qty);
            }

            else if(categoria2ComboBox.getSelectedItem().equals("Eletro")){
                EletroDAO.flag = true;
                EletroDAO.atualizarEletro(model, qty);
            }
            
            modeloAddCampo.setText("");
            atualizaQtdeCampo.setText("");
        
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
        
   
    }//GEN-LAST:event_atualizaEstoqueBtnActionPerformed

    private void atualizaQtdeCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaQtdeCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizaQtdeCampoActionPerformed

    private void removerEstoqueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerEstoqueBtnActionPerformed
        // TODO add your handling code here:
        try{
            String del = modeloDelCampo.getText();
        
        if(categoria3ComboBox.getSelectedItem().equals("Iluminação")){
            IluminacaoDAO.apagar(del);
        }
        else if(categoria3ComboBox.getSelectedItem().equals("Hidraulica")){
            HidraulicaDAO.apagar(del);
        }
        else if(categoria3ComboBox.getSelectedItem().equals("Eletro")){
            EletroDAO.apagar(del);
        }
        modeloDelCampo.setText("");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_removerEstoqueBtnActionPerformed

    private void apagarFaturamentoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarFaturamentoBtnActionPerformed
        // TODO add your handling code here:
        FaturamentoDAO.apagarFatura();
    }//GEN-LAST:event_apagarFaturamentoBtnActionPerformed

    private void precoAquisicaoCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoAquisicaoCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoAquisicaoCampoActionPerformed

    private void consultaDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaDataBtnActionPerformed
        // TODO add your handling code here:
            cardAdminParentLayout.removeAll();
            cardAdminParentLayout.add(faturamentoPanel);
            cardAdminParentLayout.repaint();
            cardAdminParentLayout.revalidate();
            
            
            DefaultTableModel model =  (DefaultTableModel) faturamentoTable.getModel();
            model.setRowCount(0);
            
            String datainicial = dataInicialCampo.getText(); 
            String datafinal = dataFinalCampo.getText();
         
            Object[] data = new Object[4];
            ArrayList<Fatura> list = new ArrayList<>();
            list = FaturamentoDAO.faturadata(datainicial, datafinal);
        
        for(int i=0; i<list.size(); i++){
            data[0] = i+1;
            data[1] = list.get(i).getUsuarioNome();
            data[2] = list.get(i).getValor();
            data[3] = list.get(i).getData();
            
            model.addRow(data);
            faturamentoTable.setRowHeight(20);
            
            int Soma = Integer.parseInt(faturamentoTable.getValueAt(i, 2)+"");
            total = total + Soma;
        
    }//GEN-LAST:event_consultaDataBtnActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apagarFaturamentoBtn;
    private javax.swing.JButton atualizaEstoqueBtn;
    private javax.swing.JTextField atualizaQtdeCampo;
    private javax.swing.JButton atualizar1Btn;
    private javax.swing.JButton atualizar2Btn;
    private javax.swing.JPanel atualizarPanel;
    private javax.swing.JPanel cardAdminParentLayout;
    private javax.swing.JComboBox<String> categoria2ComboBox;
    private javax.swing.JComboBox<String> categoria3ComboBox;
    private javax.swing.JComboBox<String> categoriaComboBox;
    private javax.swing.JButton consultaDataBtn;
    private javax.swing.JPanel controlaEstoquePanel;
    private javax.swing.JTable controlaEstoqueTable;
    private javax.swing.JButton controleEstoqueBtn;
    private javax.swing.JTextField dataFinalCampo;
    private javax.swing.JTextField dataInicialCampo;
    private javax.swing.JTextArea descricaoCampo;
    private javax.swing.JButton faturamentoBtn;
    private javax.swing.JPanel faturamentoPanel;
    private javax.swing.JTable faturamentoTable;
    private javax.swing.JButton imagemSelecionadaBtn;
    private javax.swing.JLabel imagemSelecionadaCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField localImagemCampo;
    private javax.swing.JTextField marcaCampo;
    private javax.swing.JTextField modeloAddCampo;
    private javax.swing.JTextField modeloCampo;
    private javax.swing.JTextField modeloDelCampo;
    private javax.swing.JTextField notaProcelCampo;
    private javax.swing.JTextField precoAquisicaoCampo;
    private javax.swing.JTextField precoCampo;
    private javax.swing.JTextField qtdeCampo;
    private javax.swing.JButton removerEstoqueBtn;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel trimestralLabel;
    // End of variables declaration//GEN-END:variables
}
